DECLARE
	CURSOR C1 IS SELECT CODCLIENTE IDCLIENTE, NOME NOMECLIENTE
		FROM CLIENTE;
		
		RC1 C1%ROWTYPE; -- CRIA UM REGISTRO DE UMA UNICA LINHA, COM A ESTRUTURA DO CURSOR
BEGIN
	OPEN C1;
		-- COM ROWTYPE
		FETCH C1 INTO RC1;
		DBMS_OUTPUT.PUT_LINE('Com RowType' || RC1.IDCLIENTE || ' ' || RC1.NOMECLIENTE);
		-- SEM ROWTYPE
		FETCH C1 INTO vCodigo, vNome;
		DBMS_OUTPUT.PUT_LINE('Sem RowType' || vCodigo || ' ' || vNome);
	CLOSE C1;
	
END;