CREATE TABLE EXEMPLO AS  SELECT * 
  FROM 
    (
      SELECT CD_DEPTO, NR_CARGO 
      FROM FUNC F
      )
      PIVOT
      (
        COUNT(NR_CARGO) FOR NR_CARGO IN (54,42,43,53)
        )
        ORDER BY CD_DEPTO;
        
SELECT * FROM EXEMPLO;
        
CREATE TABLE CIDAO_DELICIA AS SELECT *
FROM EXEMPLO
UNPIVOT (QTDE FOR NR_CARGO IN ("54","42","43","53"))

SELECT * FROM CIDAO_DELICIA;

SELECT IC.INDEX_NAME, IC.COLUMN_NAME,
IC.COLUMN_POSITION, IX.UNIQUENESS
FROM USER_INDEXES IX, USER_IND_COLUMNS IC
WHERE IC.INDEX_NAME = IX.INDEX_NAME
AND IC.TABLE_NAME = 'EMP';

CREATE INDEX INDICE_NOME ON FUNC (UPPER(NM_FUNC));
SELECT * FROM FUNC WHERE UPPER(NM_FUNC) = 'CRISTINA';
DROP INDEX INDICE_NOME;