create table resultado(
cod_dep number,
qtd_emp number,
vlr_sal number,
med_sal number
);

--SELECT COUNT(EMPNO) FROM EMP; -- AGRUPAMENTO SIMPLES
SELECT COUNT(SAL), SUM(SAL), (SUM(SAL)/COUNT(SAL)) FROM EMP
GROUP BY DEPTNO;


DECLARE
  CURSOR C1 IS SELECT DEPTNO, COUNT(EMPNO) QTD_EMP FROM EMP
GROUP BY DEPTNO;
  R1 C1%ROWTYPE; --VAI TER DUAS COLUNAS (DEPTNO E QUANTIDADE) REPRESENTADAS NO CURSOR (C1)
  --REMP EMP%ROWTYPE; --EXEMPLO QUE PODE SER ORIGINADO DE UMA TABELA FÍSICA
BEGIN
  OPEN C1;
    LOOP  
      FETCH C1 INTO R1;
      EXIT WHEN C1%NOTFOUND;
      INSERT INTO RESULTADO (COD_DEP,QTD_EMP) VALUES (R1.DEPTNO, R1.QTD_EMP);
    END LOOP;
  CLOSE C1;
EXCEPTION
  WHEN OTHERS THEN 
    RAISE_APPLICATION_ERROR(-20001,SQLERRM(SQLCODE));
END;

-- SELECT * FROM RESULTADO; -- VALIDAÇÃO DO RESULTADO DO CURSOR DECLARADO

DECLARE
  CURSOR C2 IS SELECT COD_DEP, VLR_SAL, MED_SAL FROM RESULTADO
  FOR UPDATE OF VLR_SAL, MED_SAL;
  v_VLR_SAL NUMBER;
  v_MED_SAL NUMBER;
BEGIN
  FOR RC2 IN C2 LOOP
    SELECT SUM(SAL), AVG(SAL) INTO v_VLR_SAL, v_MED_SAL
      FROM EMP
      WHERE DEPTNO = C2.COD_DEP;
      
  UPDATE RESULTADO
    SET VLR_SAL = v_VLR_SAL, MED_SAL = v_MED_SAL
    WHERE CURRENT OF C2;
  END LOOP;
END;

