SELECT NOMECLIENTE(2) FROM DUAL;

SELECT CODPEDIDO, CODCLIENTE, NOMECLIENTE(CODCLIENTE) AS NOME, VALORTOTAL
  FROM PEDIDO;
  
SELECT SUM(IP.QUANTIDADE) AS QUANTIDADE, SUM(IP.VALORUNITARIO * IP.QUANTIDADE) AS VALORTOTAL
  FROM PEDIDO PED
  INNER JOIN ITEMPEDIDO IP ON PED.CODPEDIDO = IP.CODPEDIDO;
