/*
CRIAR UMA FUNCTION QUE RETORNA O 
NOME DO CLIENTE DE ACORDO COM O 
CÓDIGO INFORMADO
*/
CREATE OR REPLACE FUNCTION NOMECLIENTE (pCodigo IN NUMBER) 
    RETURN VARCHAR2 IS
  vNome VARCHAR2(50);
 
BEGIN
  SELECT NOME INTO vNome FROM CLIENTE CLI
  WHERE CODCLIENTE = pCodigo;
RETURN vNome;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
  vNome := 'Cliente não cadastrado!';
  RETURN vNome;
END;
/*
CRIAR PROCEDURE QUE RECEBE CÓDIGO 
DO CLIENTE E RETORNA A QUANTIDADE DE 
ITENS COMPRADOS E O VALOR TOTAL
(ITEMPEDIDO.QUANTIDADE)
(ITEMPEDIDO.VALORUNITARIO * ITEMPEDIDO.QUANTIDADE)
*/
CREATE OR REPLACE PROCEDURE PTOTAL (pCODPEDIDO IN NUMBER, pQUANTIDADE OUT NUMBER, pTOTAL OUT NUMBER) IS
BEGIN
  SELECT SUM(IP.QUANTIDADE) AS QUANTIDADE, SUM(IP.VALORUNITARIO * IP.QUANTIDADE) AS VALORTOTAL
  INTO pQUANTIDADE, pTOTAL
  FROM PEDIDO PED
  INNER JOIN ITEMPEDIDO IP ON PED.CODPEDIDO = IP.CODPEDIDO;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
  pQUANTIDADE := 0;
  pTOTAL := 0;
  END;