/*
CREATE OR REPLACE PACKAGE PACOTE IS
FUNCTION DISPLAY (DATA IN DATE) RETURN VARCHAR2;
FUNCTION DISPLAY (TEXTO IN VARCHAR2) RETURN VARCHAR2;
FUNCTION DISPLAY (NUMERO IN NUMBER) RETURN VARCHAR2;
END PACOTE;

CREATE OR REPLACE PACKAGE BODY PACOTE IS
  FUNCTION DISPLAY (DATA IN DATE) RETURN VARCHAR2 IS
    BEGIN
      RETURN 'DATA = '||TO_CHAR(DATA, 'DD/MM/YY HH24:MI');
    END;
    
  FUNCTION DISPLAY (TEXTO IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
      RETURN 'TEXTO = '||TEXTO;
    END;
  
  FUNCTION DISPLAY (NUMERO IN NUMBER) RETURN VARCHAR2 IS
    BEGIN
      RETURN 'NUMERO = '||TO_CHAR(NUMERO,'O9R8XN342RY349M8HF934');
    END;
END PACOTE;
*/
CREATE OR REPLACE PACKAGE PACOTE_DE_VALORES IS
  FUNCTION DESCONTO(pCLIENTE IN NUMBER, PERC IN NUMBER) RETURN NUMBER;
  FUNCTION JUROS(pCLIENTE IN NUMBER, PERC IN NUMBER) RETURN NUMBER;
END PACOTE_DE_VALORES;

CREATE OR REPLACE PACKAGE BODY PACOTE_DE_VALORES IS
  FUNCTION JUROS(pCLIENTE IN NUMBER, PERC IN NUMBER) RETURN NUMBER IS
      VALOR NUMBER;
    BEGIN
      SELECT SUM(VALORTOTAL) INTO VALOR FROM PEDIDO WHERE CLIENTE = pCLIENTE;
      PERC := PERC/100;
      RETURN VALOR * PERC + VALOR;
    END;
    
  FUNCTION DESCONTO(pCLIENTE IN NUMBER, PERC IN NUMBER) RETURN NUMBER IS
      VALOR NUMBER;
    BEGIN
      SELECT SUM(VALORTOTAL) INTO VALOR FROM PEDIDO WHERE CLIENTE = pCLIENTE;
      PERC := PERC/100;
      RETURN VALOR - (VALOR * PERC);
    END;
  END PACOTE_DE_VALORES;
  
  